---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: busybox-wf-invocation
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  replicas: 1
  entrypoint: say-hello
  workflowTemplateRef:
    name: busybox-wf

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: busybox-wf
spec:
  templates:
    - name: say-hello
      inputs:
        parameters:
          - name: shard_name
          - name: bucket_name
      container:
        name: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
